.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH check 1  "check " 
.SH NAME
check \- Check repositories for various conditions, such as branch protection being enabled, stale branches, etc
.SH SYNOPSIS
\fBcheck\fR [\fB\-r\fR|\fB\-\-repository\fR] [\fB\-a\fR|\fB\-\-all\fR] [\fB\-l\fR|\fB\-\-license\fR] [\fB\-p\fR|\fB\-\-protected\fR] [\fB\-\-branch\fR] [\fB\-o\fR|\fB\-\-old\-branches\fR] [\fB\-d\fR|\fB\-\-days\-ago\fR] [\fB\-b\fR|\fB\-\-branch\-filter\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check repositories for various conditions, such as branch protection being enabled, stale branches, etc
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-repository\fR \fI<REPOSITORY>\fR
The repository to check
.TP
\fB\-a\fR, \fB\-\-all\fR
Check all repositories
.TP
\fB\-l\fR, \fB\-\-license\fR
Enable checking the license of target repositories
.TP
\fB\-p\fR, \fB\-\-protected\fR
Enable checking the protected status of the main branch for target repositories
.TP
\fB\-\-branch\fR \fI<BRANCH>\fR
Specify the branch to check. Required when \*(Aq\-\-protected\*(Aq is enabled
.TP
\fB\-o\fR, \fB\-\-old\-branches\fR
Enable checking for old branches in target repository
.TP
\fB\-d\fR, \fB\-\-days\-ago\fR \fI<DAYS_AGO>\fR [default: 30]
Number of days of inactivity after which a branch is flagged
.TP
\fB\-b\fR, \fB\-\-branch\-filter\fR \fI<BRANCH_FILTER>\fR
Regex that can be used to filter branches
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH EXTRA
EXAMPLES:
    # Check all repositories for license and branch protection
    git_sync repo check \-\-all \-\-license \-\-protected \-\-branch "ODP\-main"
    # Check a specific repository for old branches inactive for 60 days matching a specific pattern. The pattern is optional, and if not provided, all branches will be checked.
    git_sync repo check \-\-repository my\-repo \-\-old\-branches \-\-days\-ago \-\-branch\-filter "^ODP"

NOTES:
    \- At least one of \-\-license, \-\-protected, or \-\-old\-branches must be specified.
    \- Use \-\-all to apply checks to all configured repositories, or \-\-repository option to target one repository. You cannot use both at the same time.
        
