.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sync 1  "sync " 
.SH NAME
sync \- Sync repoositories
.SH SYNOPSIS
\fBsync\fR [\fB\-r\fR|\fB\-\-repository\fR] [\fB\-a\fR|\fB\-\-all\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Sync repoositories
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-repository\fR \fI<REPOSITORY>\fR
The repository to sync
.TP
\fB\-a\fR, \fB\-\-all\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
