.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH config 1  "config " 
.SH NAME
config \- Generate a default config
.SH SYNOPSIS
\fBconfig\fR [\fB\-f\fR|\fB\-\-file\fR] [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Generate a default config
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-file\fR \fI<FILE>\fR
Path to save the config file
.TP
\fB\-\-force\fR
Overwrite existing config file if it exists
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
