.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH compare 1  "compare " 
.SH NAME
compare \- Sync tags Compare tags between repositories
.SH SYNOPSIS
\fBcompare\fR [\fB\-r\fR|\fB\-\-repository\fR] [\fB\-p\fR|\fB\-\-parent\fR] [\fB\-a\fR|\fB\-\-all\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Sync tags Compare tags between repositories
.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-repository\fR \fI<REPOSITORY>\fR
The base repository to compare against
.TP
\fB\-p\fR, \fB\-\-parent\fR \fI<PARENT>\fR

.TP
\fB\-a\fR, \fB\-\-all\fR
Apply to all configured repositories
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
