.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH create 1  "create " 
.SH NAME
create \- Create a new release
.SH SYNOPSIS
\fBcreate\fR <\fB\-c\fR|\fB\-\-current\-release\fR> <\fB\-p\fR|\fB\-\-previous\-release\fR> [\fB\-r\fR|\fB\-\-repository\fR] [\fB\-\-release\-name\fR] [\fB\-l\fR|\fB\-\-latest\fR] [\fB\-a\fR|\fB\-\-all\fR] [\fB\-n\fR|\fB\-\-no\-release\-notes\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Create a new release
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-current\-release\fR \fI<CURRENT_RELEASE>\fR
The tag or branch to base the release off of
.TP
\fB\-p\fR, \fB\-\-previous\-release\fR \fI<PREVIOUS_RELEASE>\fR
The previous release tag or branch. This is used to generate the changelog
.TP
\fB\-r\fR, \fB\-\-repository\fR \fI<REPOSITORY>\fR
The repository for which to create the release
.TP
\fB\-\-release\-name\fR \fI<RELEASE_NAME>\fR
The name of the release. If not specified, the tag name will be used
.TP
\fB\-l\fR, \fB\-\-latest\fR \fI<LATEST>\fR [default: true]
Set this release to the latest
.br

.br
[\fIpossible values: \fRtrue, false, legacy]
.TP
\fB\-a\fR, \fB\-\-all\fR
Specify whether this release should use \*(Aqlegacy\*(Aq to determine if it\*(Aqs the newest release. \*(Aqlegacy\*(Aq specifies that the latest release should be determined using creation date and a higher version number Create this release for all configured repositories
.TP
\fB\-n\fR, \fB\-\-no\-release\-notes\fR
Disable release note generation. This decreases the number of api calls
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
