[advisories]
# These are both low severity vulnerabilities.
# Safe to ignore
ignore = ["RUSTSEC-2026-0098", "RUSTSEC-2026-0099"]
informational_warnings = ["unmaintained"]
severity_threshold = "high"

[output]
format = "terminal"
quiet = false
